# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/src/basic"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/src/dind"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/src/node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/src/typescript-node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/src/clasp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/src/rust-base"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/src/rust"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/src/rust-cli"
    schedule:
      interval: "weekly"
