name: Build image for devcontainer
on:
  push:

jobs:

  build_node:
    name: Build image(basic)
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare tags for image
        id: prep
        run: |
          TAG1="ghcr.io/${GITHUB_REPOSITORY}:$(date "+%Y-%m")-$(echo "${GITHUB_REF}" | sed -e 's/refs\/heads\///; s/\//-/g')-basic"
          TAG2="ghcr.io/${GITHUB_REPOSITORY}:basic"
          test "${GITHUB_REF}" = "refs/heads/main" \
            && TAGS="${TAG1}%0A${TAG2}" \
            || TAGS="${TAG1}"
          echo "::set-output name=tags::${TAGS}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image to GitHub Container Registry
        id: push_image
        uses: docker/build-push-action@v3
        with:
          context: ./basic
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
