name: test_deplpoy
on:
  push:
  repository_dispatch:
    types: [deploy_push]

jobs:
  build_node:
    name: Build image(node)
    runs-on: ubuntu-latest

    setps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare tags for image
        id: prep_prod
        run: |
          TAG1="ghcr.io/${GITHUB_REPOSITORY}:$(date "+%Y-%m")-$(echo ${GITHUB_REF} | sed -e 's/refs\/heads\///; s/\//-/g')-node"
          TAG2="ghcr.io/${GITHUB_REPOSITORY}:node"
          TAGS="${TAG1}%0A${TAG2}"
          echo "::set-output name=tags::${TAGS}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image to GitHub Container Registry
        id: push__image
        uses: docker/build-push-action@v3
        with:
          context: ./node
          push: true
          target: runner
          tags: ${{ steps.prep.outputs.tags }}
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
